"""Wazuh accuracy and tool-consistency checks for the agent skills.

- Every Wazuh rule ID cited as `rule N` / `rules N, M` must exist in the official ruleset
  (tests/fixtures/wazuh_rule_refs.json, regenerated by scripts/build_wazuh_rule_refs.py), and any level stated
  right after it must match.
- A skill's allowed-tools must be held by every agent that carries the skill.
- Every read-only Wazuh MCP tool is owned by at least one agent; no agent holds a state-changing one.
"""

import json
import pathlib
import re

from app.roster import AGENTS
from app.skills_loader import builtin_skills
from app.swarm.mcp import is_action_tool

ROOT = pathlib.Path(__file__).resolve().parents[2]
SKILLS_DIR = ROOT / "backend" / "app" / "skills"
REFS = json.loads((pathlib.Path(__file__).parent / "fixtures" / "wazuh_rule_refs.json").read_text())["rules"]
CITE = re.compile(r"(?<!custom )\brules?\s+(\d{3,6}(?:\s*(?:,|and|or|/)\s*\d{3,6})*)", re.I)
LEVEL = re.compile(r"(?<!custom )\brule\s+(\d{3,6})\b(?:(?!\brules?\b)[^.\n|]){0,30}?\blevel\s+(\d{1,2})\b", re.I)
ALWAYS = {"skills", "handoff_to_agent"}


def _md_files():
    return sorted(SKILLS_DIR.rglob("*.md"))


def test_cited_rule_ids_exist_in_official_ruleset():
    unknown = {}
    for path in _md_files():
        for m in CITE.finditer(path.read_text()):
            for rid in re.findall(r"\d{3,6}", m.group(1)):
                if int(rid) >= 100000:
                    continue  # custom range must be written as "custom rule N" (checked below)
                if rid not in REFS:
                    unknown.setdefault(rid, set()).add(str(path.relative_to(SKILLS_DIR)))
    assert not unknown, f"rule IDs not in the official ruleset (or refs not regenerated): {unknown}"


def test_stated_levels_match_official():
    wrong = []
    for path in _md_files():
        for m in LEVEL.finditer(path.read_text()):
            rid, level = m.group(1), int(m.group(2))
            if rid in REFS and REFS[rid]["level"] != level:
                wrong.append((path.parent.name, rid, level, REFS[rid]["level"]))
    assert not wrong, f"(skill, rule, stated level, official level): {wrong}"


def test_custom_rules_use_the_custom_range():
    for path in _md_files():
        for m in re.finditer(r"\bcustom rules?\s+(\d{3,6})", path.read_text(), re.I):
            assert 100000 <= int(m.group(1)) <= 120000, (path, m.group(0))


def test_skill_tools_are_held_by_every_holder():
    skills = builtin_skills()
    problems = []
    for a in AGENTS:
        have = set(a["tools"]) | ALWAYS
        for sid in a["skills"]:
            missing = set(skills[sid].allowed_tools or []) - have
            if missing:
                problems.append((a["id"], sid, sorted(missing)))
    assert not problems, problems


def test_every_agent_has_wazuh_basics():
    for a in AGENTS:
        assert "wazuh-mcp-querying" in a["skills"], a["id"]
        assert "prompt-injection-defense" in a["skills"], a["id"]


def test_mcp_read_tools_all_have_an_owner():
    tools = json.loads((ROOT / "mock-wazuh" / "mock_wazuh" / "tools.json").read_text())
    names = [t["name"] for t in (tools if isinstance(tools, list) else tools["tools"])]
    granted = {t for a in AGENTS for t in a["tools"]}
    read = [n for n in names if not is_action_tool(n)]
    assert len(names) == 55
    assert not [n for n in read if n not in granted], "unowned MCP tools"
    assert not [t for t in granted if is_action_tool(t)], "agents must never hold state-changing tools"


def test_wazuh_domain_skills_present():
    skills = builtin_skills()
    for sid in ["wazuh-mcp-querying", "wazuh-rules-and-decoders", "wazuh-fim-investigation", "wazuh-sca-hardening",
                "wazuh-malware-detection", "wazuh-windows-sysmon", "wazuh-cloud-container", "wazuh-active-response",
                "wazuh-platform-health"]:
        assert sid in skills and len(skills[sid].instructions.splitlines()) >= 50, sid
